CREATE TABLE `child_accounts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`parentId` int NOT NULL,
	`childProfileId` int,
	`ageGroup` varchar(8) NOT NULL,
	`accessCode` varchar(16) NOT NULL,
	`gender` varchar(10) NOT NULL,
	`language` varchar(5) DEFAULT 'ar',
	`parentCanSeeAdvisor` boolean DEFAULT true,
	`screenTimeLimit` int DEFAULT 0,
	`lastActive` timestamp,
	`isActive` boolean DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `child_accounts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `child_achievements` (
	`id` int AUTO_INCREMENT NOT NULL,
	`childAccountId` int NOT NULL,
	`title` varchar(255) NOT NULL,
	`description` text,
	`category` varchar(32) NOT NULL,
	`icon` varchar(64),
	`earnedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `child_achievements_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `child_activity_log` (
	`id` int AUTO_INCREMENT NOT NULL,
	`childAccountId` int NOT NULL,
	`activityType` varchar(32) NOT NULL,
	`data` json,
	`durationSeconds` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `child_activity_log_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `child_challenges` (
	`id` int AUTO_INCREMENT NOT NULL,
	`childAccountId` int NOT NULL,
	`title` varchar(255) NOT NULL,
	`description` text,
	`category` varchar(32) NOT NULL,
	`status` varchar(16) DEFAULT 'pending',
	`challengeDate` varchar(10) NOT NULL,
	`completedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `child_challenges_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `environment_analysis` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`childId` int,
	`analysisData` json,
	`sources` json,
	`autoGenerated` boolean DEFAULT true,
	`version` int DEFAULT 1,
	`analyzedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `environment_analysis_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `family_activities` (
	`id` int AUTO_INCREMENT NOT NULL,
	`familyId` int NOT NULL,
	`proposedBy` int NOT NULL,
	`title` varchar(255) NOT NULL,
	`description` text,
	`activityType` varchar(32) NOT NULL,
	`proposedDate` varchar(10),
	`status` varchar(16) DEFAULT 'proposed',
	`votes` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `family_activities_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `family_reminders` (
	`id` int AUTO_INCREMENT NOT NULL,
	`familyId` int NOT NULL,
	`createdBy` int NOT NULL,
	`title` varchar(255) NOT NULL,
	`description` text,
	`reminderType` varchar(32) NOT NULL,
	`scheduledAt` timestamp,
	`recurrence` varchar(16) DEFAULT 'none',
	`isActive` boolean DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `family_reminders_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `neighborhood_activities` (
	`id` int AUTO_INCREMENT NOT NULL,
	`groupId` int NOT NULL,
	`title` varchar(255) NOT NULL,
	`description` text,
	`activityType` varchar(32) NOT NULL,
	`scheduledAt` timestamp,
	`location` varchar(255),
	`createdBy` int NOT NULL,
	`status` varchar(16) DEFAULT 'proposed',
	`maxParticipants` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `neighborhood_activities_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `neighborhood_groups` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`city` varchar(128),
	`country` varchar(64),
	`lat` varchar(20),
	`lon` varchar(20),
	`radiusKm` int DEFAULT 5,
	`inviteCode` varchar(32) NOT NULL,
	`description` text,
	`createdBy` int NOT NULL,
	`maxMembers` int DEFAULT 50,
	`isActive` boolean DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `neighborhood_groups_id` PRIMARY KEY(`id`),
	CONSTRAINT `neighborhood_groups_inviteCode_unique` UNIQUE(`inviteCode`)
);
--> statement-breakpoint
CREATE TABLE `neighborhood_members` (
	`id` int AUTO_INCREMENT NOT NULL,
	`groupId` int NOT NULL,
	`userId` int NOT NULL,
	`role` varchar(16) DEFAULT 'member',
	`joinedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `neighborhood_members_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `peer_group_members` (
	`id` int AUTO_INCREMENT NOT NULL,
	`groupId` int NOT NULL,
	`childAccountId` int NOT NULL,
	`approvedByParentId` int,
	`approved` boolean DEFAULT false,
	`joinedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `peer_group_members_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `peer_groups` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`ageRange` varchar(8) NOT NULL,
	`gender` varchar(10) NOT NULL,
	`inviteCode` varchar(32) NOT NULL,
	`createdBy` int NOT NULL,
	`parentApproval` boolean DEFAULT true,
	`maxMembers` int DEFAULT 20,
	`isActive` boolean DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `peer_groups_id` PRIMARY KEY(`id`),
	CONSTRAINT `peer_groups_inviteCode_unique` UNIQUE(`inviteCode`)
);
--> statement-breakpoint
CREATE TABLE `shared_child_updates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`childId` int NOT NULL,
	`authorId` int NOT NULL,
	`updateType` varchar(32) NOT NULL,
	`content` text NOT NULL,
	`isRead` boolean DEFAULT false,
	`readAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `shared_child_updates_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
ALTER TABLE `partnerships` ADD `initiatedBy` int NOT NULL;--> statement-breakpoint
ALTER TABLE `partnerships` ADD `confirmed` boolean DEFAULT true;--> statement-breakpoint
ALTER TABLE `partnerships` ADD `updatedAt` timestamp DEFAULT (now()) NOT NULL ON UPDATE CURRENT_TIMESTAMP;--> statement-breakpoint
ALTER TABLE `partnerships` DROP COLUMN `createdBy`;