export const ENV = {
  host: process.env.HOST || "127.0.0.1",
  port: parseInt(process.env.PORT || "3000"),
  isProduction: process.env.NODE_ENV === "production",
  databaseUrl: process.env.DATABASE_URL || "",
  cookieSecret: process.env.JWT_SECRET || "rabbaanie-secret-change-me",
  adminEmail: process.env.ADMIN_EMAIL || "",
  adminPassword: process.env.ADMIN_PASSWORD || "",
  openrouterApiKey: process.env.OPENROUTER_API_KEY || "",
  openrouterBaseUrl: process.env.OPENROUTER_BASE_URL || "https://openrouter.ai/api/v1",
  openrouterModelEasy: process.env.OPENROUTER_MODEL_EASY || "google/gemini-3.5-flash",
  openrouterModelMedium: process.env.OPENROUTER_MODEL_MEDIUM || "anthropic/claude-sonnet-4",
  openrouterModelHard: process.env.OPENROUTER_MODEL_HARD || "anthropic/claude-opus-4.8",
  brevoApiKey: process.env.BREVO_API_KEY || "",
  brevoSender: process.env.BREVO_SENDER || "noreply@rabbaanie.com",
  appUrl: process.env.APP_URL || "https://api.rabbaanie.com",
  googleClientId: process.env.GOOGLE_CLIENT_ID || "",
  googleClientSecret: process.env.GOOGLE_CLIENT_SECRET || "",
};
