import { Share, Platform } from "react-native";

/**
 * Generate a formatted text dossier for a child.
 * Since native PDF generation requires heavy libraries not available in Expo Go,
 * we generate a well-formatted text document that can be shared via the system share sheet.
 * On production builds, this could be extended with react-native-html-to-pdf.
 */

interface ChildDossierData {
  child: {
    name: string;
    birthDate?: string;
    gender?: string;
    publicId?: string;
  };
  environment?: {
    livingWith?: string;
    siblings?: number;
    school?: string;
    specialNeeds?: string;
    notes?: string;
    [key: string]: any;
  };
  issues?: Array<{
    description: string;
    createdAt?: string;
    treatmentPlan?: string;
  }>;
  weekPlan?: {
    weekId?: string;
    goals?: Array<{ phase: string; title: string; status?: string }>;
  };
  notes?: Array<{
    title: string;
    content: string;
    category: string;
    createdAt: string;
  }>;
  language: "nl" | "en" | "ar";
}

function tx(lang: "nl" | "en" | "ar", nl: string, en: string, ar: string): string {
  return lang === "ar" ? ar : lang === "en" ? en : nl;
}

export function generateChildDossier(data: ChildDossierData): string {
  const { child, environment, issues, weekPlan, notes, language: lang } = data;
  const divider = "═".repeat(50);
  const subDivider = "─".repeat(40);
  const now = new Date().toLocaleDateString(lang === "ar" ? "ar-SA" : lang === "en" ? "en-US" : "nl-NL", {
    day: "numeric", month: "long", year: "numeric"
  });

  let doc = "";

  // Header
  doc += `${divider}\n`;
  doc += `  ${tx(lang, "KINDDOSSIER", "CHILD DOSSIER", "ملف الطفل")}\n`;
  doc += `  ${tx(lang, "Rabbaanie", "Rabbaanie", "ربّانيّ")}\n`;
  doc += `  ${tx(lang, "Datum", "Date", "التاريخ")}: ${now}\n`;
  doc += `${divider}\n\n`;

  // Child profile
  doc += `▶ ${tx(lang, "PROFIEL", "PROFILE", "الملف الشخصي")}\n`;
  doc += `${subDivider}\n`;
  doc += `  ${tx(lang, "Naam", "Name", "الاسم")}: ${child.name}\n`;
  if (child.publicId) doc += `  ID: ${child.publicId}\n`;
  if (child.birthDate) doc += `  ${tx(lang, "Geboortedatum", "Birth date", "تاريخ الميلاد")}: ${child.birthDate}\n`;
  if (child.gender) doc += `  ${tx(lang, "Geslacht", "Gender", "الجنس")}: ${child.gender}\n`;
  doc += "\n";

  // Environment
  if (environment) {
    doc += `▶ ${tx(lang, "OMGEVING", "ENVIRONMENT", "البيئة")}\n`;
    doc += `${subDivider}\n`;
    if (environment.livingWith) doc += `  ${tx(lang, "Woonsituatie", "Living with", "يعيش مع")}: ${environment.livingWith}\n`;
    if (environment.siblings !== undefined) doc += `  ${tx(lang, "Broers/zussen", "Siblings", "الإخوة")}: ${environment.siblings}\n`;
    if (environment.school) doc += `  ${tx(lang, "School", "School", "المدرسة")}: ${environment.school}\n`;
    if (environment.specialNeeds) doc += `  ${tx(lang, "Bijzonderheden", "Special needs", "احتياجات خاصة")}: ${environment.specialNeeds}\n`;
    if (environment.notes) doc += `  ${tx(lang, "Notities", "Notes", "ملاحظات")}: ${environment.notes}\n`;
    doc += "\n";
  }

  // Issues & treatment plans
  if (issues && issues.length > 0) {
    doc += `▶ ${tx(lang, "ISSUES & BEHANDELPLANNEN", "ISSUES & TREATMENT PLANS", "المشكلات وخطط العلاج")}\n`;
    doc += `${subDivider}\n`;
    issues.forEach((issue, i) => {
      doc += `  ${i + 1}. ${issue.description}\n`;
      if (issue.treatmentPlan) {
        doc += `     ${tx(lang, "Behandelplan", "Treatment plan", "خطة العلاج")}:\n`;
        doc += `     ${issue.treatmentPlan.split("\n").join("\n     ")}\n`;
      }
      doc += "\n";
    });
  }

  // Week plan
  if (weekPlan && weekPlan.goals && weekPlan.goals.length > 0) {
    doc += `▶ ${tx(lang, "WEEKPLAN", "WEEK PLAN", "الخطة الأسبوعية")} ${weekPlan.weekId || ""}\n`;
    doc += `${subDivider}\n`;
    weekPlan.goals.forEach((goal) => {
      const status = goal.status === "done" ? "✓" : goal.status === "partial" ? "◐" : "○";
      doc += `  ${status} [${goal.phase}] ${goal.title}\n`;
    });
    doc += "\n";
  }

  // Chat notes
  if (notes && notes.length > 0) {
    doc += `▶ ${tx(lang, "GESPREKSNOTITIES", "CHAT NOTES", "ملاحظات المحادثة")}\n`;
    doc += `${subDivider}\n`;
    notes.forEach((note) => {
      const date = new Date(note.createdAt).toLocaleDateString(lang === "ar" ? "ar-SA" : "nl-NL", { day: "numeric", month: "short", year: "numeric" });
      doc += `  [${note.category.toUpperCase()}] ${note.title} (${date})\n`;
      doc += `  ${note.content}\n\n`;
    });
  }

  // Footer
  doc += `${divider}\n`;
  doc += `  ${tx(lang, "Gegenereerd door Rabbaanie", "Generated by Rabbaanie", "تم إنشاؤه بواسطة ربّانيّ")}\n`;
  doc += `  ${tx(lang, "Dit document is vertrouwelijk", "This document is confidential", "هذا المستند سري")}\n`;
  doc += `${divider}\n`;

  return doc;
}

export async function shareChildDossier(dossier: string, childName: string, lang: "nl" | "en" | "ar") {
  try {
    await Share.share({
      message: dossier,
      title: tx(lang, `Dossier ${childName}`, `Dossier ${childName}`, `ملف ${childName}`),
    });
  } catch {
    // Silently fail
  }
}
