// Surah list with start pages (Mushaf Madina) — extracted from
// app/(tabs)/concepts.tsx so it can be imported directly by tests (precise
// count/first/last assertions) without parsing the screen's source text.

export interface Surah {
  number: number;
  name: string;
  englishName: string;
  startPage: number;
  numberOfAyahs: number;
  revelationType: string;
}

export const SURAH_LIST: Surah[] = [
  {
    number: 1,
    name: "الفاتحة",
    englishName: "Al-Faatiha",
    startPage: 1,
    numberOfAyahs: 7,
    revelationType: "Meccan",
  },
  {
    number: 2,
    name: "البقرة",
    englishName: "Al-Baqara",
    startPage: 2,
    numberOfAyahs: 286,
    revelationType: "Medinan",
  },
  {
    number: 3,
    name: "آل عمران",
    englishName: "Aal-i-Imraan",
    startPage: 50,
    numberOfAyahs: 200,
    revelationType: "Medinan",
  },
  {
    number: 4,
    name: "النساء",
    englishName: "An-Nisaa",
    startPage: 77,
    numberOfAyahs: 176,
    revelationType: "Medinan",
  },
  {
    number: 5,
    name: "المائدة",
    englishName: "Al-Maaida",
    startPage: 106,
    numberOfAyahs: 120,
    revelationType: "Medinan",
  },
  {
    number: 6,
    name: "الأنعام",
    englishName: "Al-An'aam",
    startPage: 128,
    numberOfAyahs: 165,
    revelationType: "Meccan",
  },
  {
    number: 7,
    name: "الأعراف",
    englishName: "Al-A'raaf",
    startPage: 151,
    numberOfAyahs: 206,
    revelationType: "Meccan",
  },
  {
    number: 8,
    name: "الأنفال",
    englishName: "Al-Anfaal",
    startPage: 177,
    numberOfAyahs: 75,
    revelationType: "Medinan",
  },
  {
    number: 9,
    name: "التوبة",
    englishName: "At-Tawba",
    startPage: 187,
    numberOfAyahs: 129,
    revelationType: "Medinan",
  },
  {
    number: 10,
    name: "يونس",
    englishName: "Yunus",
    startPage: 208,
    numberOfAyahs: 109,
    revelationType: "Meccan",
  },
  {
    number: 11,
    name: "هود",
    englishName: "Hud",
    startPage: 221,
    numberOfAyahs: 123,
    revelationType: "Meccan",
  },
  {
    number: 12,
    name: "يوسف",
    englishName: "Yusuf",
    startPage: 235,
    numberOfAyahs: 111,
    revelationType: "Meccan",
  },
  {
    number: 13,
    name: "الرعد",
    englishName: "Ar-Ra'd",
    startPage: 249,
    numberOfAyahs: 43,
    revelationType: "Medinan",
  },
  {
    number: 14,
    name: "إبراهيم",
    englishName: "Ibrahim",
    startPage: 255,
    numberOfAyahs: 52,
    revelationType: "Meccan",
  },
  {
    number: 15,
    name: "الحجر",
    englishName: "Al-Hijr",
    startPage: 262,
    numberOfAyahs: 99,
    revelationType: "Meccan",
  },
  {
    number: 16,
    name: "النحل",
    englishName: "An-Nahl",
    startPage: 267,
    numberOfAyahs: 128,
    revelationType: "Meccan",
  },
  {
    number: 17,
    name: "الإسراء",
    englishName: "Al-Israa",
    startPage: 282,
    numberOfAyahs: 111,
    revelationType: "Meccan",
  },
  {
    number: 18,
    name: "الكهف",
    englishName: "Al-Kahf",
    startPage: 293,
    numberOfAyahs: 110,
    revelationType: "Meccan",
  },
  {
    number: 19,
    name: "مريم",
    englishName: "Maryam",
    startPage: 305,
    numberOfAyahs: 98,
    revelationType: "Meccan",
  },
  {
    number: 20,
    name: "طه",
    englishName: "Taa-Haa",
    startPage: 312,
    numberOfAyahs: 135,
    revelationType: "Meccan",
  },
  {
    number: 21,
    name: "الأنبياء",
    englishName: "Al-Anbiyaa",
    startPage: 322,
    numberOfAyahs: 112,
    revelationType: "Meccan",
  },
  {
    number: 22,
    name: "الحج",
    englishName: "Al-Hajj",
    startPage: 332,
    numberOfAyahs: 78,
    revelationType: "Medinan",
  },
  {
    number: 23,
    name: "المؤمنون",
    englishName: "Al-Mu'minoon",
    startPage: 342,
    numberOfAyahs: 118,
    revelationType: "Meccan",
  },
  {
    number: 24,
    name: "النور",
    englishName: "An-Noor",
    startPage: 350,
    numberOfAyahs: 64,
    revelationType: "Medinan",
  },
  {
    number: 25,
    name: "الفرقان",
    englishName: "Al-Furqaan",
    startPage: 359,
    numberOfAyahs: 77,
    revelationType: "Meccan",
  },
  {
    number: 26,
    name: "الشعراء",
    englishName: "Ash-Shu'araa",
    startPage: 367,
    numberOfAyahs: 227,
    revelationType: "Meccan",
  },
  {
    number: 27,
    name: "النمل",
    englishName: "An-Naml",
    startPage: 377,
    numberOfAyahs: 93,
    revelationType: "Meccan",
  },
  {
    number: 28,
    name: "القصص",
    englishName: "Al-Qasas",
    startPage: 385,
    numberOfAyahs: 88,
    revelationType: "Meccan",
  },
  {
    number: 29,
    name: "العنكبوت",
    englishName: "Al-Ankaboot",
    startPage: 396,
    numberOfAyahs: 69,
    revelationType: "Meccan",
  },
  {
    number: 30,
    name: "الروم",
    englishName: "Ar-Room",
    startPage: 404,
    numberOfAyahs: 60,
    revelationType: "Meccan",
  },
  {
    number: 31,
    name: "لقمان",
    englishName: "Luqman",
    startPage: 411,
    numberOfAyahs: 34,
    revelationType: "Meccan",
  },
  {
    number: 32,
    name: "السجدة",
    englishName: "As-Sajda",
    startPage: 415,
    numberOfAyahs: 30,
    revelationType: "Meccan",
  },
  {
    number: 33,
    name: "الأحزاب",
    englishName: "Al-Ahzaab",
    startPage: 418,
    numberOfAyahs: 73,
    revelationType: "Medinan",
  },
  {
    number: 34,
    name: "سبأ",
    englishName: "Saba",
    startPage: 428,
    numberOfAyahs: 54,
    revelationType: "Meccan",
  },
  {
    number: 35,
    name: "فاطر",
    englishName: "Faatir",
    startPage: 434,
    numberOfAyahs: 45,
    revelationType: "Meccan",
  },
  {
    number: 36,
    name: "يس",
    englishName: "Yaseen",
    startPage: 440,
    numberOfAyahs: 83,
    revelationType: "Meccan",
  },
  {
    number: 37,
    name: "الصافات",
    englishName: "As-Saaffaat",
    startPage: 446,
    numberOfAyahs: 182,
    revelationType: "Meccan",
  },
  {
    number: 38,
    name: "ص",
    englishName: "Saad",
    startPage: 453,
    numberOfAyahs: 88,
    revelationType: "Meccan",
  },
  {
    number: 39,
    name: "الزمر",
    englishName: "Az-Zumar",
    startPage: 458,
    numberOfAyahs: 75,
    revelationType: "Meccan",
  },
  {
    number: 40,
    name: "غافر",
    englishName: "Ghaafir",
    startPage: 467,
    numberOfAyahs: 85,
    revelationType: "Meccan",
  },
  {
    number: 41,
    name: "فصلت",
    englishName: "Fussilat",
    startPage: 477,
    numberOfAyahs: 54,
    revelationType: "Meccan",
  },
  {
    number: 42,
    name: "الشورى",
    englishName: "Ash-Shooraa",
    startPage: 483,
    numberOfAyahs: 53,
    revelationType: "Meccan",
  },
  {
    number: 43,
    name: "الزخرف",
    englishName: "Az-Zukhruf",
    startPage: 489,
    numberOfAyahs: 89,
    revelationType: "Meccan",
  },
  {
    number: 44,
    name: "الدخان",
    englishName: "Ad-Dukhaan",
    startPage: 496,
    numberOfAyahs: 59,
    revelationType: "Meccan",
  },
  {
    number: 45,
    name: "الجاثية",
    englishName: "Al-Jaathiya",
    startPage: 499,
    numberOfAyahs: 37,
    revelationType: "Meccan",
  },
  {
    number: 46,
    name: "الأحقاف",
    englishName: "Al-Ahqaaf",
    startPage: 502,
    numberOfAyahs: 35,
    revelationType: "Meccan",
  },
  {
    number: 47,
    name: "محمد",
    englishName: "Muhammad",
    startPage: 507,
    numberOfAyahs: 38,
    revelationType: "Medinan",
  },
  {
    number: 48,
    name: "الفتح",
    englishName: "Al-Fath",
    startPage: 511,
    numberOfAyahs: 29,
    revelationType: "Medinan",
  },
  {
    number: 49,
    name: "الحجرات",
    englishName: "Al-Hujuraat",
    startPage: 515,
    numberOfAyahs: 18,
    revelationType: "Medinan",
  },
  {
    number: 50,
    name: "ق",
    englishName: "Qaaf",
    startPage: 518,
    numberOfAyahs: 45,
    revelationType: "Meccan",
  },
  {
    number: 51,
    name: "الذاريات",
    englishName: "Adh-Dhaariyat",
    startPage: 520,
    numberOfAyahs: 60,
    revelationType: "Meccan",
  },
  {
    number: 52,
    name: "الطور",
    englishName: "At-Toor",
    startPage: 523,
    numberOfAyahs: 49,
    revelationType: "Meccan",
  },
  {
    number: 53,
    name: "النجم",
    englishName: "An-Najm",
    startPage: 526,
    numberOfAyahs: 62,
    revelationType: "Meccan",
  },
  {
    number: 54,
    name: "القمر",
    englishName: "Al-Qamar",
    startPage: 528,
    numberOfAyahs: 55,
    revelationType: "Meccan",
  },
  {
    number: 55,
    name: "الرحمن",
    englishName: "Ar-Rahmaan",
    startPage: 531,
    numberOfAyahs: 78,
    revelationType: "Medinan",
  },
  {
    number: 56,
    name: "الواقعة",
    englishName: "Al-Waaqia",
    startPage: 534,
    numberOfAyahs: 96,
    revelationType: "Meccan",
  },
  {
    number: 57,
    name: "الحديد",
    englishName: "Al-Hadid",
    startPage: 537,
    numberOfAyahs: 29,
    revelationType: "Medinan",
  },
  {
    number: 58,
    name: "المجادلة",
    englishName: "Al-Mujaadila",
    startPage: 542,
    numberOfAyahs: 22,
    revelationType: "Medinan",
  },
  {
    number: 59,
    name: "الحشر",
    englishName: "Al-Hashr",
    startPage: 545,
    numberOfAyahs: 24,
    revelationType: "Medinan",
  },
  {
    number: 60,
    name: "الممتحنة",
    englishName: "Al-Mumtahana",
    startPage: 549,
    numberOfAyahs: 13,
    revelationType: "Medinan",
  },
  {
    number: 61,
    name: "الصف",
    englishName: "As-Saff",
    startPage: 551,
    numberOfAyahs: 14,
    revelationType: "Medinan",
  },
  {
    number: 62,
    name: "الجمعة",
    englishName: "Al-Jumu'a",
    startPage: 553,
    numberOfAyahs: 11,
    revelationType: "Medinan",
  },
  {
    number: 63,
    name: "المنافقون",
    englishName: "Al-Munaafiqoon",
    startPage: 554,
    numberOfAyahs: 11,
    revelationType: "Medinan",
  },
  {
    number: 64,
    name: "التغابن",
    englishName: "At-Taghaabun",
    startPage: 556,
    numberOfAyahs: 18,
    revelationType: "Medinan",
  },
  {
    number: 65,
    name: "الطلاق",
    englishName: "At-Talaaq",
    startPage: 558,
    numberOfAyahs: 12,
    revelationType: "Medinan",
  },
  {
    number: 66,
    name: "التحريم",
    englishName: "At-Tahrim",
    startPage: 560,
    numberOfAyahs: 12,
    revelationType: "Medinan",
  },
  {
    number: 67,
    name: "الملك",
    englishName: "Al-Mulk",
    startPage: 562,
    numberOfAyahs: 30,
    revelationType: "Meccan",
  },
  {
    number: 68,
    name: "القلم",
    englishName: "Al-Qalam",
    startPage: 564,
    numberOfAyahs: 52,
    revelationType: "Meccan",
  },
  {
    number: 69,
    name: "الحاقة",
    englishName: "Al-Haaqqa",
    startPage: 566,
    numberOfAyahs: 52,
    revelationType: "Meccan",
  },
  {
    number: 70,
    name: "المعارج",
    englishName: "Al-Ma'aarij",
    startPage: 568,
    numberOfAyahs: 44,
    revelationType: "Meccan",
  },
  {
    number: 71,
    name: "نوح",
    englishName: "Nooh",
    startPage: 570,
    numberOfAyahs: 28,
    revelationType: "Meccan",
  },
  {
    number: 72,
    name: "الجن",
    englishName: "Al-Jinn",
    startPage: 572,
    numberOfAyahs: 28,
    revelationType: "Meccan",
  },
  {
    number: 73,
    name: "المزمل",
    englishName: "Al-Muzzammil",
    startPage: 574,
    numberOfAyahs: 20,
    revelationType: "Meccan",
  },
  {
    number: 74,
    name: "المدثر",
    englishName: "Al-Muddaththir",
    startPage: 575,
    numberOfAyahs: 56,
    revelationType: "Meccan",
  },
  {
    number: 75,
    name: "القيامة",
    englishName: "Al-Qiyaama",
    startPage: 577,
    numberOfAyahs: 40,
    revelationType: "Meccan",
  },
  {
    number: 76,
    name: "الإنسان",
    englishName: "Al-Insaan",
    startPage: 578,
    numberOfAyahs: 31,
    revelationType: "Medinan",
  },
  {
    number: 77,
    name: "المرسلات",
    englishName: "Al-Mursalaat",
    startPage: 580,
    numberOfAyahs: 50,
    revelationType: "Meccan",
  },
  {
    number: 78,
    name: "النبأ",
    englishName: "An-Naba",
    startPage: 582,
    numberOfAyahs: 40,
    revelationType: "Meccan",
  },
  {
    number: 79,
    name: "النازعات",
    englishName: "An-Naazi'aat",
    startPage: 583,
    numberOfAyahs: 46,
    revelationType: "Meccan",
  },
  {
    number: 80,
    name: "عبس",
    englishName: "Abasa",
    startPage: 585,
    numberOfAyahs: 42,
    revelationType: "Meccan",
  },
  {
    number: 81,
    name: "التكوير",
    englishName: "At-Takwir",
    startPage: 586,
    numberOfAyahs: 29,
    revelationType: "Meccan",
  },
  {
    number: 82,
    name: "الانفطار",
    englishName: "Al-Infitaar",
    startPage: 587,
    numberOfAyahs: 19,
    revelationType: "Meccan",
  },
  {
    number: 83,
    name: "المطففين",
    englishName: "Al-Mutaffifin",
    startPage: 587,
    numberOfAyahs: 36,
    revelationType: "Meccan",
  },
  {
    number: 84,
    name: "الانشقاق",
    englishName: "Al-Inshiqaaq",
    startPage: 589,
    numberOfAyahs: 25,
    revelationType: "Meccan",
  },
  {
    number: 85,
    name: "البروج",
    englishName: "Al-Burooj",
    startPage: 590,
    numberOfAyahs: 22,
    revelationType: "Meccan",
  },
  {
    number: 86,
    name: "الطارق",
    englishName: "At-Taariq",
    startPage: 591,
    numberOfAyahs: 17,
    revelationType: "Meccan",
  },
  {
    number: 87,
    name: "الأعلى",
    englishName: "Al-A'laa",
    startPage: 591,
    numberOfAyahs: 19,
    revelationType: "Meccan",
  },
  {
    number: 88,
    name: "الغاشية",
    englishName: "Al-Ghaashiya",
    startPage: 592,
    numberOfAyahs: 26,
    revelationType: "Meccan",
  },
  {
    number: 89,
    name: "الفجر",
    englishName: "Al-Fajr",
    startPage: 593,
    numberOfAyahs: 30,
    revelationType: "Meccan",
  },
  {
    number: 90,
    name: "البلد",
    englishName: "Al-Balad",
    startPage: 594,
    numberOfAyahs: 20,
    revelationType: "Meccan",
  },
  {
    number: 91,
    name: "الشمس",
    englishName: "Ash-Shams",
    startPage: 595,
    numberOfAyahs: 15,
    revelationType: "Meccan",
  },
  {
    number: 92,
    name: "الليل",
    englishName: "Al-Lail",
    startPage: 595,
    numberOfAyahs: 21,
    revelationType: "Meccan",
  },
  {
    number: 93,
    name: "الضحى",
    englishName: "Ad-Dhuhaa",
    startPage: 596,
    numberOfAyahs: 11,
    revelationType: "Meccan",
  },
  {
    number: 94,
    name: "الشرح",
    englishName: "Ash-Sharh",
    startPage: 596,
    numberOfAyahs: 8,
    revelationType: "Meccan",
  },
  {
    number: 95,
    name: "التين",
    englishName: "At-Tin",
    startPage: 597,
    numberOfAyahs: 8,
    revelationType: "Meccan",
  },
  {
    number: 96,
    name: "العلق",
    englishName: "Al-Alaq",
    startPage: 597,
    numberOfAyahs: 19,
    revelationType: "Meccan",
  },
  {
    number: 97,
    name: "القدر",
    englishName: "Al-Qadr",
    startPage: 598,
    numberOfAyahs: 5,
    revelationType: "Meccan",
  },
  {
    number: 98,
    name: "البينة",
    englishName: "Al-Bayyina",
    startPage: 598,
    numberOfAyahs: 8,
    revelationType: "Medinan",
  },
  {
    number: 99,
    name: "الزلزلة",
    englishName: "Az-Zalzala",
    startPage: 599,
    numberOfAyahs: 8,
    revelationType: "Medinan",
  },
  {
    number: 100,
    name: "العاديات",
    englishName: "Al-Aadiyaat",
    startPage: 599,
    numberOfAyahs: 11,
    revelationType: "Meccan",
  },
  {
    number: 101,
    name: "القارعة",
    englishName: "Al-Qaari'a",
    startPage: 600,
    numberOfAyahs: 11,
    revelationType: "Meccan",
  },
  {
    number: 102,
    name: "التكاثر",
    englishName: "At-Takaathur",
    startPage: 600,
    numberOfAyahs: 8,
    revelationType: "Meccan",
  },
  {
    number: 103,
    name: "العصر",
    englishName: "Al-Asr",
    startPage: 601,
    numberOfAyahs: 3,
    revelationType: "Meccan",
  },
  {
    number: 104,
    name: "الهمزة",
    englishName: "Al-Humaza",
    startPage: 601,
    numberOfAyahs: 9,
    revelationType: "Meccan",
  },
  {
    number: 105,
    name: "الفيل",
    englishName: "Al-Fil",
    startPage: 601,
    numberOfAyahs: 5,
    revelationType: "Meccan",
  },
  {
    number: 106,
    name: "قريش",
    englishName: "Quraish",
    startPage: 602,
    numberOfAyahs: 4,
    revelationType: "Meccan",
  },
  {
    number: 107,
    name: "الماعون",
    englishName: "Al-Maa'oon",
    startPage: 602,
    numberOfAyahs: 7,
    revelationType: "Meccan",
  },
  {
    number: 108,
    name: "الكوثر",
    englishName: "Al-Kawthar",
    startPage: 602,
    numberOfAyahs: 3,
    revelationType: "Meccan",
  },
  {
    number: 109,
    name: "الكافرون",
    englishName: "Al-Kaafiroon",
    startPage: 603,
    numberOfAyahs: 6,
    revelationType: "Meccan",
  },
  {
    number: 110,
    name: "النصر",
    englishName: "An-Nasr",
    startPage: 603,
    numberOfAyahs: 3,
    revelationType: "Medinan",
  },
  {
    number: 111,
    name: "المسد",
    englishName: "Al-Masad",
    startPage: 603,
    numberOfAyahs: 5,
    revelationType: "Meccan",
  },
  {
    number: 112,
    name: "الإخلاص",
    englishName: "Al-Ikhlaas",
    startPage: 604,
    numberOfAyahs: 4,
    revelationType: "Meccan",
  },
  {
    number: 113,
    name: "الفلق",
    englishName: "Al-Falaq",
    startPage: 604,
    numberOfAyahs: 5,
    revelationType: "Meccan",
  },
  {
    number: 114,
    name: "الناس",
    englishName: "An-Naas",
    startPage: 604,
    numberOfAyahs: 6,
    revelationType: "Meccan",
  },
];
